# Things I believe

- Conservative politics are evil
- There is no god
- A belief in god is harmful
- Programming is an art
- Self improvement is possible
- Rationality is the best way we know of to self improve
- Goal factoring is useful
- I enjoy programming but don't want to do it for the rest of my life
- Rape jokes are not OK
- I am generally a good person
- For the most part, people like me
- Everyone has something to teach you, but some people have much more to teach you than others
- Most people are stupid
- Most people are bad at generalizing
- I am more intelligent than the majority of the population
- The universe is deterministic
- Reductionism can always describe wholistic truths
- The mind is not magical and obeys computational laws
- I am mostly heterosexual
- I have few true friends
- I am bad at making friends
- I am handsome
- Money is not something I particularly desire
- Grim Fandango had a profound effect on my life
- Russia is my ideal home
- Almost all politicians are crooked
- I can accomplish anything I set my mind to
- I am getting better at life
- There is infinity utility in the world if you know where to look
- I am remarkably different from the social norm
- I would rather know the truth than a comforting lie
- No human problem is fundamentally unsolvable 
- MWI is correct
- People quickly bore me
- Intimate connections can be made with the strangest of people
- No one has life figured out
- Kolomogorov complexity is a fantastic means of believing things
- Being polyphasic is ultimately a good thing for me
- Drinking improves social interactions
- Knowledge is power
- Fairness, truth and liberty are good ideals
- In an ideal world, we would have no need for justice
- The political landscape is fundamentally broken
- Humans are exceptionally bad at developing systems
- The AI singularity will happen in the next 500 years
- The biggest limiting factor to humans is their perception of their ability
- The women to whom I am sexually attracted and to whom I am emotionally attracted are, for the most part, mutually exclusive groups
- Most philosophers are full of shit